// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC3ZpkDBNs_lpjHZgJPC0eOSTFd7Zz1pY',
    appId: '1:141501917171:web:68c0f47d10d832a6e85486',
    messagingSenderId: '141501917171',
    projectId: 'minimal-4d478',
    authDomain: 'minimal-4d478.firebaseapp.com',
    storageBucket: 'minimal-4d478.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvfxtcWFjSNa-c0BT1aFzJ32PR74rmmTE',
    appId: '1:141501917171:android:4dbe5a5079535527e85486',
    messagingSenderId: '141501917171',
    projectId: 'minimal-4d478',
    storageBucket: 'minimal-4d478.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2RsqPbtbYzQrtWTaO-AnOvP5oGvHX7xE',
    appId: '1:141501917171:ios:7a72e3666fb88daae85486',
    messagingSenderId: '141501917171',
    projectId: 'minimal-4d478',
    storageBucket: 'minimal-4d478.appspot.com',
    iosBundleId: 'com.example.minimalSocial',
  );
}
