// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDt1G0ntaZi37h2ehiKvId-p37X7EU2ro',
    appId: '1:186274021742:web:d0bf7c9cd11b440b1e417f',
    messagingSenderId: '186274021742',
    projectId: 'crud-362c3',
    authDomain: 'crud-362c3.firebaseapp.com',
    storageBucket: 'crud-362c3.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2M-azaRj2Ak09WaN7CNxUr1AG9AmmwCs',
    appId: '1:186274021742:ios:9b2cf862042285be1e417f',
    messagingSenderId: '186274021742',
    projectId: 'crud-362c3',
    storageBucket: 'crud-362c3.appspot.com',
    iosBundleId: 'com.example.firebaseCrud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDt1G0ntaZi37h2ehiKvId-p37X7EU2ro',
    appId: '1:186274021742:web:bd491f7f0b5012db1e417f',
    messagingSenderId: '186274021742',
    projectId: 'crud-362c3',
    authDomain: 'crud-362c3.firebaseapp.com',
    storageBucket: 'crud-362c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2M-azaRj2Ak09WaN7CNxUr1AG9AmmwCs',
    appId: '1:186274021742:ios:9b2cf862042285be1e417f',
    messagingSenderId: '186274021742',
    projectId: 'crud-362c3',
    storageBucket: 'crud-362c3.appspot.com',
    iosBundleId: 'com.example.firebaseCrud',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH-0l1_PR1MnsH9Sttuwgn4vePCrs2Kcw',
    appId: '1:186274021742:android:42afc160df6933561e417f',
    messagingSenderId: '186274021742',
    projectId: 'crud-362c3',
    storageBucket: 'crud-362c3.appspot.com',
  );

}